version: '3.8'

services:
  app:
    # build . will create the image such as a previous command typed.
    build: 
      context: .
      dockerfile: Dockerfile
    # container_name: iotdatauser
    ports:
      - 3333:3333
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes:
      - .:/user/app # will send everything to the workdir created previously
      - .:/app
    # network_mode: host
    depends_on:
      - database
  database:
    container_name: iotdatauser
    image: mysql:5.7.31
    restart: always
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=iotdatauser
      # - MYSQL_USER=uqac
      # - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    # volumes:
    #   - mysqldata:/data/mysql
    # network_mode: host
    

      
# volumes:
#   mysqldata:
#     driver: local